server:
  port: 8080
  servlet:
    context-path: /sample-sp

logging:
  level:
    root: info
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: debug
    org.opensaml.xmlsec: debug

spring:
  security:
    saml2:
      relyingparty:
        registration:
          samlexample:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.cer"
            identityprovider:
              singlesignon:
                sign-request: false
              entity-id: codetinkering.com
              sso-url: http://localhost:8081/sample-idp/saml/idp/select
              metadata-uri: http://localhost:8081/sample-idp/saml/idp/metadata
#              verification.credentials:
#                - certificate-location: "classpath:credentials/identity-provider-certificate.crt"
